// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertLength(arg1:number,arg2:number,arg3:number):Promise<string>;

export function Greet(arg1:string):Promise<string>;
