// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertLength(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertLength'](arg1, arg2, arg3);
}

export function ConvertTemperature(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertTemperature'](arg1, arg2, arg3);
}

export function ConvertWeight(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertWeight'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
